# Generated by Django 4.1.1 on 2022-12-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
