# Generated by Django 4.1.1 on 2022-12-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0002_delete_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_netland',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('serie.series',),
        ),
    ]
