# Generated by Django 4.1.1 on 2022-12-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0004_delete_test_netland_test_netland'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_netland',
        ),
    ]
