# Generated by Django 4.1.1 on 2022-12-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0006_test_netland'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_netland',
        ),
    ]
