# Generated by Django 4.1.1 on 2022-12-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0008_test_netland'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test_netland',
            options={},
        ),
    ]
