# Generated by Django 4.1.1 on 2022-12-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serie', '0009_alter_test_netland_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test_netland',
            options={'managed': False},
        ),
    ]
