name: Check MacOS compatibility

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
      - stable/*
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  macos-deps:
    name: Install dev dependencies on MacOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements/*.txt'
      - name: Install OS-level packages
        run: |
          brew install pkg-config
      - name: Install dependencies
        run: |
          export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/
          pip install -r requirements/dev.txt \
            --use-pep517 \
            --use-feature=no-binary-enable-wheel-cache
        env:
          STATIC_DEPS: 'true'
